### ISSUE TITLE
Configure to run on file save

### ISSUE THREAD

**Issue by duyn9uyen** [JeremyCaron/vscode-csharp-organize-usings#10]
Is there an option to run this when a file is saved?

**Comment by JeremyCaron** [comment]
Hey @duyn9uyen - not built into this extension natively, but I use the same setup you're describing via the "[Run on Save](https://marketplace.visualstudio.com/items?itemName=pucelle.run-on-save)" extension by pucelle.

Here's the setting snippet you'll need to connect the two:

```
    "runOnSave.commands": [
        {
            "match": ".*\\.cs$",
            "commandBeforeSaving": "csharpOrganizeUsings.organize",
            "runIn": "vscode"
        }
    ]
```

I'll try to remember to add this to the README on the next release.  Please let me know if this works out for you and if it does I'll close out the issue.

**Comment by jeremy-allocate** [comment]
Closing, no response from OP.

**Comment by JeremyCaron** [comment]
Closing, no response from OP.

**Comment by duyn9uyen** [comment]
Sorry @JeremyCaron, forgot about this. I just tried your snipped with the Run On Save extension by pucelle and it didn't seem to run the "Organize Using" command.

**Comment by duyn9uyen** [comment]
This [Run It On ](https://marketplace.visualstudio.com/items?itemName=fsevenm.run-it-on) extension seems to work with the following snippet:

```
"runItOn": {
        "commands": [
            {
                "match": ".*\\.cs$",
                "isShellCommand" : false,
                "cmd": "csharpOrganizeUsings.organize"
            }
        ]
    }
```

**Comment by JeremyCaron** [comment]
Strange, what I sent you works here but glad you found something equivalent 🎉 

I'll see if I can figure that out before updating the readme to suggest one of these extensions over the other.

**Comment by duyn9uyen** [comment]
I appreciate your help!
