### ISSUE TITLE
Implement CodeAction for codeActionsOnSave

### ISSUE THREAD

**Issue by hrobertson** [JeremyCaron/vscode-csharp-organize-usings#11]
If the extension exposed a CodeAction via a CodeActionsProvider then it would be able to be invoked on save without the need for 3rd party extensions as discussed in https://github.com/JeremyCaron/vscode-csharp-organize-usings/issues/10.

Example settings json:
```json
"[csharp]": {
    "editor.codeActionsOnSave": [
        "csharpOrganizeUsings.organize"
    ],
}
```
See https://code.visualstudio.com/api/references/vscode-api#languages.registerCodeActionsProvider

**Comment by JeremyCaron** [comment]
I will definitely look into this for 1.0.5, thanks for the tip @hrobertson

**Comment by JeremyCaron** [comment]
1.0.5 has been released today.  You were mostly right about the setting you'll need, it's:

```
"[csharp]": {
    "editor.codeActionsOnSave": [
        "source.organizeImports"
    ]
}
```

Thanks again for the idea.

**Comment by JeremyCaron** [comment]
Done.
